const data = {
    products:[
        {
            _id:'1',
            name:'Nike Bomber Jacket',
            category:'jackets',
            image: '/images/p1.PNG',
            price: 299,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id:'2',
            name:'Adidas fit shirt',
            category:'Shirts',
            image: '/images/p2.PNG',
            price: 60,
            brand: 'Adidas',
            rating: 3.3,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id:'3',
            name:'peter England Shirt',
            category:'Shirts',
            image: '/images/p3.PNG',
            price: 50,
            brand: 'Peter England',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id:'4',
            name:'Lee Jeans',
            category:'Pants',
            image: '/images/p4.PNG',
            price: 424,
            brand: 'Lee',
            rating: 4.9,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id:'5',
            name:'Nike Jeans',
            category:'Pants',
            image: '/images/p5.PNG',
            price: 30,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id:'6',
            name:'THE Jeans',
            category:'Pants',
            image: '/images/p6.PNG',
            price: 55,
            brand: 'Nike',
            rating: 4,
            numReviews: 10,
            description: 'High quality product',
        },
    ],
};

export default data;
